name: Generate macOS Installer

on:
  workflow_dispatch:
    inputs:
      macos_version:
        type: choice
        description: "macOS Version"
        required: true
        options:
          - Sonoma v14.6.1
          - Ventura v13.6.9
          - Monterey v12.7.6
          - Big Sur v11.7.10
          - Catalina v10.15.7
          - Mojave v10.14.6
          - High Sierra v10.13.6
      # file:
      #   type: choice
      #   description: "File Type"
      #   required: true
      #   options:
      #     - iso
      #     - dmg
      #     - zip

run-name: Generate macOS Installer - ${{ github.event.inputs.macos_version }} ${{ github.event.inputs.file }}

env:
  installer_version: "" # Do not touch: Populated by extract-details (suppresses warnings)
  installer_name: "" # Do not touch: Populated by extract-details (suppresses warnings)

jobs:
  build:
    runs-on: macos-12
    if: github.repository == 'LoSunny/Download-macOS'
    steps:
      - uses: actions/checkout@v4
      
      # Setup
      - name: Extract Version Details
        id: extract-details
        run: |
          string="${{ github.event.inputs.macos_version }}"
          echo "installer_version=${string//*v/}" >> $GITHUB_ENV
          echo "installer_name=${string// v*/}" >> $GITHUB_ENV

      # Download Installer
      - name: Download macOS Installer
        run: |
          softwareupdate --fetch-full-installer --full-installer-version ${{ env.installer_version }}

      # Generate Installer
      - name: Generate macOS Setup Files 5G
        run: |
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 5120m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 5.5G
        if: ${{ failure() }}
        run: |
          sudo hdiutil eject -force /Volumes/'${{ env.installer_name }}'
          sudo rm -f /tmp/'${{ env.installer_name }}'
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 5632m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 6G
        if: ${{ failure() }}
        run: |
          sudo hdiutil eject -force /Volumes/'${{ env.installer_name }}'
          sudo rm -f /tmp/'${{ env.installer_name }}'
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 6144m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Installer
        run: |
          sleep 100
          hdiutil eject -force /Volumes/'Install macOS ${{ env.installer_name }}'
          
          hdiutil convert /tmp/'${{ env.installer_name }}'.dmg -format UDTO -o ~/Desktop/'${{ env.installer_name }}'
          mv -v ~/Desktop/'${{ env.installer_name }}'.cdr ~/Desktop/'${{ env.installer_name }}'.iso
          shasum -a 256 ~/Desktop/'${{ env.installer_name }}.iso' > ~/Desktop/'${{ env.installer_name }}.iso.sha256'
          
          sudo mv /tmp/'${{ env.installer_name }}'.dmg ~/Desktop/'${{ env.installer_name }}'.dmg
          shasum -a 256 ~/Desktop/'${{ env.installer_name }}.dmg' > ~/Desktop/'${{ env.installer_name }}.dmg.sha256'

          cd /Applications
          zip -r 'Install macOS ${{ env.installer_name }}.zip' 'Install macOS ${{ env.installer_name }}.app'
          mv -v 'Install macOS ${{ env.installer_name }}.zip' ~/Desktop/'${{ env.installer_name }}.zip'
          shasum -a 256 ~/Desktop/'${{ env.installer_name }}.zip' > ~/Desktop/'${{ env.installer_name }}.zip.sha256'

      # Extract hash
      - name: Extract Version Details
        run: |
          echo "iso_hash=$(cat ~/Desktop/'${{ env.installer_name }}.iso.sha256')" >> $GITHUB_ENV
          echo "dmg_hash=$(cat ~/Desktop/'${{ env.installer_name }}.iso.sha256')" >> $GITHUB_ENV
          echo "zip_hash=$(cat ~/Desktop/'${{ env.installer_name }}.zip.sha256')" >> $GITHUB_ENV

      # Upload Installer
      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: macOS ${{ env.installer_name }}.dmg
          path: "~/Desktop/${{ env.installer_name }}.dmg"
          compression-level: '9'

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: macOS ${{ env.installer_name }}.iso
          path: "~/Desktop/${{ env.installer_name }}.iso"
          compression-level: '9'

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: macOS ${{ env.installer_name }}.zip
          path: "~/Desktop/${{ env.installer_name }}.zip"
          compression-level: '9'

      # Upload Hash
      - name: Upload DMG Hash
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.installer_name }} ${{ env.iso_hash }}.dmg.sha256"
          path: "~/Desktop/${{ env.installer_name }}.dmg.sha256"
          compression-level: '9'

      - name: Upload ISO Hash
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.installer_name }} ${{ env.iso_hash }}.iso.sha256"
          path: "~/Desktop/${{ env.installer_name }}.iso.sha256"
          compression-level: '9'

      - name: Upload ZIP Hash
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.installer_name }} ${{ env.iso_hash }}.zip.sha256"
          path: "~/Desktop/${{ env.installer_name }}.zip.sha256"
          compression-level: '9'
