name: Generate macOS Installer

on:
  workflow_dispatch:
    inputs:
      macos_version:
        type: choice
        description: "macOS Version"
        required: true
        options:
          - Sonoma v14.6.1
          - Ventura v13.6.9
          - Monterey v12.7.6
          - Big Sur v11.7.10
          - Catalina v10.15.7
          - Mojave v10.14.6
          - High Sierra v10.13.6
      # file:
      #   type: choice
      #   description: "File Type"
      #   required: true
      #   options:
      #     - iso
      #     - dmg
      #     - zip

run-name: Generate macOS Installer - ${{ github.event.inputs.macos_version }} ${{ github.event.inputs.file }}

env:
  installer_version: "" # Do not touch: Populated by extract-details (suppresses warnings)
  installer_name: "" # Do not touch: Populated by extract-details (suppresses warnings)

jobs:
  build:
    runs-on: macos-12
    if: github.repository == 'LoSunny/Download-macOS'
    steps:
      - uses: actions/checkout@v4
      
      # Setup
      - name: Extract Version Details
        id: extract-details
        run: |
          string="${{ github.event.inputs.macos_version }}"
          echo "installer_version=${string//*v/}" >> $GITHUB_ENV
          echo "installer_name=${string// v*/}" >> $GITHUB_ENV

      # Download Installer
      - name: Download macOS Installer
        run: |
          softwareupdate --fetch-full-installer --full-installer-version ${{ env.installer_version }}

      # Generate Installer
      - name: Generate macOS Setup Files 5.5G
        id: setup-55
        run: |
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 5632m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 6G
        id: setup-6
        if: ${{ failure() && steps.setup-55.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 6144m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 6.5G
        id: setup-65
        if: ${{ failure() && steps.setup-6.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 6656m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 7G
        id: setup-7
        if: ${{ failure() && steps.setup-65.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 7168m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 7.5G
        id: setup-75
        if: ${{ failure() && steps.setup-7.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 7680m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 8G
        id: setup-8
        if: ${{ failure() && steps.setup-75.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 8192m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 8.5G
        id: setup-85
        if: ${{ failure() && steps.setup-8.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 8704m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 9G
        id: setup-9
        if: ${{ failure() && steps.setup-85.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 9216m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 9.5G
        id: setup-95
        if: ${{ failure() && steps.setup-9.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 9728m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 10G
        id: setup-10
        if: ${{ failure() && steps.setup-95.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 10240m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 10.5G
        id: setup-105
        if: ${{ failure() && steps.setup-10.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 10752m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 11G
        id: setup-11
        if: ${{ failure() && steps.setup-105.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 11264m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 11.5G
        id: setup-115
        if: ${{ failure() && steps.setup-11.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 11776m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 12G
        id: setup-12
        if: ${{ failure() && steps.setup-115.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 12288m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 12.5G
        id: setup-125
        if: ${{ failure() && steps.setup-12.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 12800m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 13G
        id: setup-13
        if: ${{ failure() && steps.setup-125.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 13312m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 13.5G
        id: setup-135
        if: ${{ failure() && steps.setup-13.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 13824m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 14G
        id: setup-14
        if: ${{ failure() && steps.setup-135.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 14336m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 14.5G
        id: setup-145
        if: ${{ failure() && steps.setup-14.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 14848m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Setup Files 15G
        id: setup-15
        if: ${{ failure() && steps.setup-145.conclusion == 'failure' }}
        run: |
          sudo rm -f /tmp/'${{ env.installer_name }}'.dmg
          sleep 10
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 15360m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction

      - name: Generate macOS Installer
        if: ${{ !cancelled() }}
        run: |
          sleep 100
          hdiutil eject -force /Volumes/'Install macOS ${{ env.installer_name }}'
          
          hdiutil convert /tmp/'${{ env.installer_name }}'.dmg -format UDTO -o ~/Desktop/'${{ env.installer_name }}'
          mv -v ~/Desktop/'${{ env.installer_name }}'.cdr ~/Desktop/'${{ env.installer_name }}'.iso
          shasum -a 256 ~/Desktop/'${{ env.installer_name }}.iso' > ~/Desktop/'${{ env.installer_name }}.iso.sha256'
          
          sudo mv /tmp/'${{ env.installer_name }}'.dmg ~/Desktop/'${{ env.installer_name }}'.dmg
          shasum -a 256 ~/Desktop/'${{ env.installer_name }}.dmg' > ~/Desktop/'${{ env.installer_name }}.dmg.sha256'

          cd /Applications
          zip -r 'Install macOS ${{ env.installer_name }}.zip' 'Install macOS ${{ env.installer_name }}.app'
          mv -v 'Install macOS ${{ env.installer_name }}.zip' ~/Desktop/'${{ env.installer_name }}.zip'
          shasum -a 256 ~/Desktop/'${{ env.installer_name }}.zip' > ~/Desktop/'${{ env.installer_name }}.zip.sha256'

      # Extract hash
      - name: Extract Version Details
        if: ${{ !cancelled() }}
        run: |
          echo "iso_hash=$(cat ~/Desktop/'${{ env.installer_name }}.iso.sha256' | cut -d ' ' -f1)" >> $GITHUB_ENV
          echo "dmg_hash=$(cat ~/Desktop/'${{ env.installer_name }}.dmg.sha256' | cut -d ' ' -f1)" >> $GITHUB_ENV
          echo "zip_hash=$(cat ~/Desktop/'${{ env.installer_name }}.zip.sha256' | cut -d ' ' -f1)" >> $GITHUB_ENV

      # Upload Installer
      - name: Upload DMG
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: macOS ${{ env.installer_name }}.dmg
          path: "~/Desktop/${{ env.installer_name }}.dmg"
          compression-level: '9'

      - name: Upload ISO
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: macOS ${{ env.installer_name }}.iso
          path: "~/Desktop/${{ env.installer_name }}.iso"
          compression-level: '9'

      - name: Upload ZIP
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: macOS ${{ env.installer_name }}.zip
          path: "~/Desktop/${{ env.installer_name }}.zip"
          compression-level: '9'

      # Upload Hash
      - name: Upload DMG Hash
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.installer_name }} ${{ env.iso_hash }}.dmg.sha256"
          path: "~/Desktop/${{ env.installer_name }}.dmg.sha256"
          compression-level: '9'

      - name: Upload ISO Hash
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.installer_name }} ${{ env.iso_hash }}.iso.sha256"
          path: "~/Desktop/${{ env.installer_name }}.iso.sha256"
          compression-level: '9'

      - name: Upload ZIP Hash
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.installer_name }} ${{ env.iso_hash }}.zip.sha256"
          path: "~/Desktop/${{ env.installer_name }}.zip.sha256"
          compression-level: '9'
